[settings]
experimental = true
disable_backends = ["asdf", "vfox"]

idiomatic_version_file_enable_tools = []

[tools]
node = "lts"
python = "3.14"
uv = "latest"

github-cli = "latest"
op = "latest"
docker-cli = "latest"
lima = "latest"
colima = "latest"
kubectl = "latest"
minikube = "latest"
kubectx = "0.9.5"
kustomize = "latest"
helm = "latest"

"npm:@openai/codex" = "latest"
"npm:@google/gemini-cli" = "latest"

"npm:bash-language-server" = "5.6.0"
"npm:yaml-language-server" = "1.19.2"
"npm:typescript-language-server" = "5.0.1"
"npm:typescript" = "latest"
"pipx:python-lsp-server" = "1.13.1"
"go:golang.org/x/tools/gopls" = "latest"
terraform-ls = "latest"
